name: bookly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  device_preview: ^1.3.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Tagesschrift
      fonts:
        - asset: assets/fonts/Tagesschrift.ttf
    - family: LibreBaskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville.ttf

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#100B20"
  android_12:
    color: "#ffffff"
    color_dark: "#100B20"